### ISSUE TITLE
email link broken.

### ISSUE THREAD

**Issue by indyaah** [avinassh/saveourcinema#2]
Tried to figure out and fix but couldn't. :(

Hope someone knows what's the problem and how to fix it.
![screenshot from 2016-02-14 22-42-11](https://cloud.githubusercontent.com/assets/1032931/13036614/33dd9dac-d36c-11e5-8b5e-1cfd64a71fd2.png)

**Comment by cdax** [comment]
Working for me. Could you provide some steps to reproduce this?

**Comment by avinassh** [comment]
@indyaah it happens when you have configured default email as Gmail in Chrome (or in system settings). Try a different browser and let me know if that works.

**Comment by indyaah** [comment]
@cdax  : Google chrome, and gmail as default email client.
@avinassh : Yes, will try and let know by midnight (GMT)
